**Numpy** : 

It is a linear algebra library for python in which we can perform various operations for a large amount of data. NumPy stands for Numerical Python. It has following features : 

**POWERFUL N-DIMENSIONAL ARRAYS** : Fast and versatile, the NumPy vectorization, indexing, and broadcasting concepts are the de-facto standards of array computing today.

**NUMERICAL COMPUTING TOOLS** : NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.

**INTEROPERABLE** : NumPy supports a wide range of hardware and computing platforms, and plays well with distributed, GPU, and sparse array libraries.

**PERFORMANT** : The core of NumPy is well-optimized C code. Enjoy the flexibility of Python with the speed of compiled code.

**EASY TO USE** : NumPy’s high level syntax makes it accessible and productive for programmers from any background or experience level.

**OPEN SOURCE** : Distributed under a liberal BSD license, NumPy is developed and maintained publicly on GitHub by a vibrant, responsive, and diverse community.


##**Advantages over normal lists**

You may think, we already have python lists with us to use. So why should we ever opt for NumPy? Let us see some advantages of NumPy over normal python lists.

In [ ]:
import numpy as np
import sys

li_arr = [i for i in range(100)]     # Create list of 100 elements
np_arr = np.arange(100)              # Create numpy array of 100 elements

In [ ]:
## Size of 100 elements in numpy array
print(np_arr.itemsize * np_arr.size)

800


In [ ]:
## Size of 100 elements in python list
print(sys.getsizeof(1) * len(li_arr))

2800


###**Time Execution**

NumPy arrays are much faster as compared to python list. We can easily verify this.

In [ ]:
import time
import numpy as np 

In [ ]:
size = 100000

In [ ]:
def addition_using_list():
  t1 = time.time()
  a = range(size)
  b = range(size)
  c = [a[i] + b[i] for i in range(size)]
  t2 = time.time()
  return t2 - t1

In [9]:
# Vectorisation
def addition_using_numpy(): 
  t1 = time.time()
  a = np.arange(size)
  b = np.arange(size)
  c = a + b
  t2 = time.time()
  return t2 - t1

In [10]:
t_list = addition_using_list()
t_numpy = addition_using_numpy()
print("List = ", t_list * 1000)   
print("NumPy = ", t_numpy * 1000)

List =  36.91887855529785
NumPy =  0.6325244903564453


###**Convinient to Use**

It is much easier to perform basic operations in NumPy arrays

##**Why is NumPy Faster Than Lists?**

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

##**Creating NumPy Arrays**

In [1]:
import numpy as np    ## Use np as an alias for numpy

###**np.array()**

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

**Syntax**

    numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)

**Parameters**

1. **object :** array_like

    An array, any object exposing the array interface, an object whose __array__ method returns an array, or any (nested) sequence.

2. **dtype :** data-type, optional

    The desired data-type for the array. If not given, then the type will be determined as the minimum type required to hold the objects in the sequence.

3. **copy :** bool, optional

    If true (default), then the object is copied. Otherwise, a copy will only be made if __array__ returns a copy, if obj is a nested sequence, or if a copy is needed to satisfy any of the other requirements (dtype, order, etc.).

In [2]:
a = [1, 2, 3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
a = [1, 2, 3, '5', 4.5]
b = np.array(a, dtype = str)
print(b)

['1' '2' '3' '5' '4.5']


In [4]:
a = [1, 2, 3, '5', 4.5]
b = np.array(a * 3)
print(b)

['1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5']


###**np.ones()**

**Syntax**

    numpy.ones(shape, dtype=None, order='C', *, like=None)

This function returns a new array of given shape and type, filled with ones.

**Parameters**
1. **shape :** int or sequence of ints

    Shape of the new array, e.g., (2, 3) or 2.

2. **dtype :** data-type, optional

    The desired data-type for the array, e.g., numpy.int8. Default is numpy.float64.

3. **order :** {‘C’, ‘F’}, optional, default: C

    Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.
  
4. **like :** array_like

    Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the __array_function__ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.

In [5]:
b = np.ones(3, dtype = int)
b

array([1, 1, 1])

In [6]:
b = np.ones((2, 3), dtype = int)
b

array([[1, 1, 1],
       [1, 1, 1]])

###**np.zeros()**

**Syntax**

    numpy.zeros(shape, dtype=float, order='C', *, like=None)

This returns a new array of given shape and type, filled with zeros.

**Parameters**
1. **shape :** int or tuple of ints

    Shape of the new array, e.g., (2, 3) or 2.

1. **dtype :** data-type, optional

    The desired data-type for the array, e.g., numpy.int8. Default is numpy.float64.

3. **order :** {‘C’, ‘F’}, optional, default: ‘C’

    Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.


In [7]:
b = np.zeros(3, dtype = int)
b

array([0, 0, 0])

In [8]:
b = np.zeros((3, 4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

###**np.full()**

**Syntax**

    numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)

Return a new array of given shape and type, filled with fill_value.

**Parameters**
1. **shape :** int or sequence of ints

    Shape of the new array, e.g., (2, 3) or 2.

2. **fill_value :** scalar or array_like

    Fill value.

3. **dtype :** data-type, optional

    The desired data-type for the array The default, None, means
    np.array(fill_value).dtype.

3. **order :** {‘C’, ‘F’}, optional

    Whether to store multidimensional data in C- or Fortran-contiguous (row- or column-wise) order in memory.

In [9]:
b = np.full((3, 3), 5, dtype = float)
b

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

###**np.empty()**

**Syntax**

    numpy.empty(shape, dtype=float, order='C', *, like=None)

This returns a new array of given shape and type, without initializing entries.

**Parameters**
1. **shape :** int or tuple of int

    Shape of the empty array, e.g., (2, 3) or 2.

2. **dtype :** data-type, optional

    Desired output data-type for the array, e.g, numpy.int8. Default is numpy.float64.

3. **order :** {‘C’, ‘F’}, optional, default: ‘C’

    Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.


In [10]:
np.empty([2, 2])             # uninitialized

array([[5.e-324, 5.e-324],
       [5.e-324, 0.e+000]])

In [12]:
np.empty([2, 2], dtype=int)              # uninitialized

array([[           58845824,                   0],
       [ 144115188126187520, 8286623315485786112]])

**Note:** You will get a different result each time you execute using empty, as the array formed will always be uninitialised.