## NumPy 2D array

Given a 2D list, create a numpy 2D array using it.

Note: Given 2D list is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Print the Numpy array.

Output Format :

numpyArray

In [1]:
import numpy as np

li = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array = np.array(li)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## NumPy 0s and 1s

Create an integer array of size 10, where all the values should be 0 but the fifth value should be 1.

Print the elements of array.

Output Format :

element1 element2 element3 ... 

In [2]:
import numpy as np
array = np.zeros(10, dtype = int)
array[4] = 1
for i in array:
    print(i, end = " ")

0 0 0 0 1 0 0 0 0 0 

## NumPy Inclusive

Create an array with values ranging consecutively from 9 to 49 (both inclusive).

Print the Numpy array.

Output Format :

element1 element2 element3 ...

In [6]:
import numpy as np
array = np.arange(9, 50, 1)
for i in array:
    print(i, end = " ")

9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 

## Identity Matrix

Create a matrix having diagonal elements as 1 and all other elements as 0 of size (5, 6).

Print the Numpy array.

Output Format :

numpyArray

In [7]:
import numpy as np
print(np.eye(5, 6, dtype = int))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


## Cut the Rope

You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.

Note:Array elements are the points where cut is to be made and round upto 2 decimal place.

Print the array element.

Output Format :

element1 

element2 

element3

In [8]:
import numpy as np

start = 0
end = 5
points = 10

for i in np.linspace(start, end, points)[1 : 9]:
    print(format(i, '.2f'))

0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


## Print Elements

Given a 2D integer array size (4, 5) with name input_? Print elements of highlighted matrix

In [9]:
import numpy as np

input_ = np.arange(1, 21, 1)
input_ = input_.reshape(4, 5)

##input_[2, 0:3]
for i in range(3):
    print(input_[2][i], end = " ")
print()

##input_[1:4, 3]
for i in range(1, 4):
    print(input_[i][3], end = " ")
print()

##input_[2:4, :]
for i in range(2, 4):
    for j in range(0, 5):
        print(input_[i][j], end = " ")
print()

##input_[1:3, 1:3]
for i in range(1, 3):
    for j in range(1, 3):
        print(input_[i][j], end = " ")

11 12 13 
9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 

## Non-Zero elements

Find indices of non-zero elements from the array [1,2,0,0,4,0] ?

Print the index of non-zero elements.

Output Format :

index1 index2 index3 ... 

In [12]:
import numpy as np
array = np.array([1, 2, 0, 0, 4, 0])
for i in np.where(array != 0)[0]:  # numpy.where() - returns array, dtype
    print(i, end = ' ')

0 1 4 

## Multiples of 3

Given an integer array of size 10. Print the index of elements which are multiple of 3.

Generate the following array [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]

Print the index of elements.

Output Format :
    
index1 index2 index3 ... 

In [14]:
import numpy as np

array = np.arange(1, 20, 2)
for i in np.where(array % 3 == 0)[0]:
    print(i, end = " ")

1 4 7 

## Odd elements

Given an integer array of size 10. Replace the odd number in numpy array with -1 ?

Note: Generate the following array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    
Print the Numpy array.

Output Format :
    
firstElement secondElement  ... 

In [15]:
import numpy as np

array = np.arange(1, 11, 1)
array[array % 2  != 0] = -1

for i in array:
    print(i, end = " ")

-1 2 -1 4 -1 6 -1 8 -1 10 

## Replace Max

Given an integer array of size 9 and replace the first occurrence of maximum value by 0?

Note: Generate the following array [11, 2, 13, 4, 15, 6, 27, 8, 19]

Print the Numpy array.

Output Format :

firstElement

secondElement 


In [18]:
import numpy as np

array = np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
index = array.argmax()  # numpy.argmax() - returns the indices of the maximum values along an axis
array[index] = 0

for i in array:
    print(i)

11
2
13
4
15
6
0
8
19


## Negate Elements

Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?

Note: Generate the following array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Print the Numpy array.

Output Format :

firstElement secondElement  

In [20]:
import numpy as np

array = np.arange(1, 11, 1)
index = np.where((array >= 3) & (array <= 8))

for i in index:
    array[i] = np.negative(array[i])
for i in array:
    print(i, end = " ")

1 2 -3 -4 -5 -6 -7 -8 9 10 

## Height

Given age and height of 20 students in two different numpy arrays with name age and height (in cms). Print the age of those students whose height is above 155 cm.

Print the Numpy array.

Output Format :
    
age1 height1 

age2 height2 


In [24]:
import numpy as np

age = np.array([15, 17, 19, 20, 14, 21, 16, 19, 13, 20, 22, 23, 21, 16, 18, 19, 20, 15, 17, 18])
height = np.array([156, 144, 180, 162, 152, 157, 154, 155, 151, 150, 158, 179, 126, 182, 183, 154, 159, 160, 172, 149])

index = np.where(height > 155)

for i in range(len(index[0])):
    print(age[index[0][i]], height[index[0][i]])

15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


## Sort by column

Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.

That means, we should re-arrange complete row based on 2nd columns' values.

Given 2D array is:

 [[21 20 19 18 17]
 
  [16 15 14 13 12]
  
  [11 10  9  8  7]
  
  [ 6  5  4  3  2]]
  
Print the 2D array in sorted order.

Note you have to generate the 2D Array.Here 2nd column means column present at index 1.

Output Format :

[[ 6  5  4  3  2]

[11 10  9  8  7]

[16 15 14 13 12]

[21 20 19 18 17]]

In [25]:
import numpy as np

array = np.arange(21, 1, -1)
array = array.reshape(4, 5)
array = array[array[:, 1].argsort()]  # numpy.argsort() - returns the indices that would sort an array
print(array)

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


When you say arr[:, n] -  (n) th column

When you say arr[n, :] - (n) th row

## Given file "terrorismData.csv"

It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period

## Killed in USA



Find value of killed column only where country == ‘United States’?

Print 0 in place of missing values.

Print count of Killed as integer value.

Output Format :

Killed1

Killed2

Killed3

Killed4

. . .

In [31]:
import numpy as np
import csv

path = 'terrorismData.csv'
killed = []

with open(path, 'r', encoding = "utf8") as data:
    reader = csv.DictReader(data)
    for row in reader:
        if row['Country'] == 'United States':
            killed.append(row['Killed'])

killed = np.array(killed)

# replacing null values with 0
killed[killed == ''] = 0

# converting string to float value
killed = np.array(killed, dtype = float)

for i in killed:
    print(int(i))

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
2
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
4
0
1
1
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0


## Total Killed in USA

Find total number of people killed from USA?

Note: Some columns of killed are empty so replace them by 0.
    
Print count of Killed as integer value.

Output Format :
    
TotalKilled

In [33]:
import numpy as np
import csv

path = 'terrorismData.csv'
killed = []

with open(path, 'r', encoding = "utf8") as data:
    reader = csv.DictReader(data)
    for row in reader:
        if row['Country'] == 'United States':
            killed.append(row['Killed'])

killed = np.array(killed)

# replacing null values with 0
killed[killed == ''] = 0

# converting string to float value
killed = np.array(killed, dtype = float)

total_killed = np.sum(killed)
print(int(total_killed))

3771
